services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: todo
    volumes:
      - todoVol:/var/lib/mysql
    networks:
      - todo-network

  myapp:
    container_name: myapp
    image: ludo2025/todo:latest
    ports:
      - 8083:8082
    environment:
      MYSQL_PASS: ${MYSQL_PASS}
    networks:
      - todo-network
    depends_on:
      - mysql
networks:
  todo-network:
    driver: bridge

volumes:
  todoVol:
